#!/bin/sh

# 自定义配置
wlan_name="OpenWrt"
wlan_password="1234512345"
root_password="1234512345"
lan_ip_address="192.168.6.1/24"   # 适配 OpenWrt 25.12.0 的 CIDR 格式

exec >/tmp/setup.log 2>&1

# 1. 修复 vnt.lua 文件中的 util -> xml（如果存在）
if [ -f /usr/lib/lua/luci/model/cbi/vnt.lua ]; then
    sed -i 's/util/xml/g' /usr/lib/lua/luci/model/cbi/vnt.lua
    echo "Fixed vnt.lua: replaced 'util' with 'xml'"
else
    echo "Warning: /usr/lib/lua/luci/model/cbi/vnt.lua not found, skip fix"
fi

# 2. 设置 root 密码
if [ -n "$root_password" ]; then
    (echo "$root_password"; sleep 1; echo "$root_password") | passwd > /dev/null
    echo "Root password set."
fi

# 3. 配置 LAN IP（CIDR 格式，OpenWrt 25.12.0 兼容）
if [ -n "$lan_ip_address" ]; then
    uci set network.lan.ipaddr="$lan_ip_address"
    uci commit network
    echo "LAN IP set to $lan_ip_address"
fi

# 4. 配置 DHCP（顺序分配 + 地址池）
uci set dhcp.lan.start='100'
uci set dhcp.lan.limit='150'
uci set dhcp.@dnsmasq[0].sequential_ip='1'
uci commit dhcp
echo "DHCP set to sequential allocation, pool 192.168.6.100-249"

# 5. 无线配置（完整保留所有参数，适配你的设备）
# 5.1 radio0 (5GHz) 设备参数
uci set wireless.radio0.type='mac80211'
uci set wireless.radio0.path='platform/soc@0/c000000.wifi'
uci set wireless.radio0.band='5g'
uci set wireless.radio0.channel='36'
uci set wireless.radio0.htmode='HE80'
uci set wireless.radio0.country='CN'
uci set wireless.radio0.disabled='0'
uci set wireless.radio0.cell_density='0'

# 5.2 radio1 (2.4GHz) 设备参数
uci set wireless.radio1.type='mac80211'
uci set wireless.radio1.path='platform/soc@0/c000000.wifi+1'
uci set wireless.radio1.band='2g'
uci set wireless.radio1.channel='6'
uci set wireless.radio1.htmode='HT20'
uci set wireless.radio1.country='CN'
uci set wireless.radio1.disabled='0'
uci set wireless.radio1.cell_density='0'
uci set wireless.radio1.txpower='20'

# 5.3 default_radio0 (5G 接口)
uci set wireless.default_radio0.device='radio0'
uci set wireless.default_radio0.network='lan'
uci set wireless.default_radio0.mode='ap'
uci set wireless.default_radio0.ssid="$wlan_name"
uci set wireless.default_radio0.encryption='psk2+ccmp'
uci set wireless.default_radio0.key="$wlan_password"
uci set wireless.default_radio0.disabled='0'
uci set wireless.default_radio0.ieee80211k='1'
uci set wireless.default_radio0.time_advertisement='2'
uci set wireless.default_radio0.time_zone='CST-8'
uci set wireless.default_radio0.wnm_sleep_mode='1'
uci set wireless.default_radio0.wnm_sleep_mode_no_keys='1'
uci set wireless.default_radio0.bss_transition='1'
uci set wireless.default_radio0.proxy_arp='1'

# 5.4 default_radio1 (2.4G 接口)
uci set wireless.default_radio1.device='radio1'
uci set wireless.default_radio1.network='lan'
uci set wireless.default_radio1.mode='ap'
uci set wireless.default_radio1.ssid="$wlan_name"
uci set wireless.default_radio1.encryption='psk2+ccmp'
uci set wireless.default_radio1.key="$wlan_password"
uci set wireless.default_radio1.disabled='0'
uci set wireless.default_radio1.ieee80211k='1'
uci set wireless.default_radio1.time_advertisement='2'
uci set wireless.default_radio1.time_zone='CST-8'
uci set wireless.default_radio1.wnm_sleep_mode='1'
uci set wireless.default_radio1.wnm_sleep_mode_no_keys='1'
uci set wireless.default_radio1.bss_transition='1'
uci set wireless.default_radio1.proxy_arp='1'

uci commit wireless
echo "Wireless configured: SSID='$wlan_name', encryption=psk2+ccmp, all extra settings applied"

# 6. 重启相关服务
/etc/init.d/network restart
/etc/init.d/dnsmasq restart
/etc/init.d/wireless restart

echo "All done! Configuration applied."
exit 0
